[tool.poetry]
name = 'T1Prep'
version = '0.1.0'
description = 'T1 PREProcessing Pipeline (aka PyCAT)'
authors = ['Christian Gaser <christian.gaser@uni-jena.de>']
license = 'Apache-2.0'
readme = 'README.md'
repository = 'https://github.com/ChristianGaser/T1Prep'
classifiers = [
    'Programming Language :: Python :: 3',
    'Operating System :: OS Independent',
    'Intended Audience :: Science/Research'
]
exclude = ['Makefile']

[tool.poetry.dependencies]
python = '^3.8'
torch = '>=1.11.0'
deepbet = '>=1.0.2'
torchreg = '>=0.1.2'

[tool.poetry.dev-dependencies]
scipy = '*'

[tool.poetry.scripts]

[build-system]
requires = ['poetry-core']
build-backend = 'poetry.core.masonry.api'