#! /bin/bash

########################################################
# global parameters
########################################################
version='parallelize v1.01'

time=`date "+%Y%b%d_%H%M"`
MEM_LIMIT=0

########################################################
# run main
########################################################

main ()
{
  parse_args ${1+"$@"}
  check_files
  if [ "$MEM_LIMIT" -gt 0 ]; then
    get_no_processes
  else
    get_no_of_cpus
  fi
  parallelize

  exit 0
}

########################################################
# check arguments and files
########################################################

parse_args ()
{
  local optname optarg
  count=0
  while [ $# -gt 0 ]
  do
    optname="`echo $1 | sed 's,=.*,,'`"
    optarg="$2"
    case "$1" in
        --command* | -c*)
            exit_if_empty "$optname" "$optarg"
            COMMAND=$optarg
            shift
            ;;
        --mem-limit* | -m*)
            exit_if_empty "$optname" "$optarg"
            MEM_LIMIT=$optarg
            shift
            ;;
        --processes* | -p*)
            exit_if_empty "$optname" "$optarg"
            NUMBER_OF_JOBS=$optarg
            shift
            ;;
        --logdir* | -l*)
            exit_if_empty "$optname" "$optarg"
            LOGDIR=$optarg
            shift
            ;;
        --test* | -t*)
            TEST=1
            ;;
        -h | --help | -v | --version | -V)
            help
            exit 1
            ;;
        -*)
            echo "`basename $0`: ERROR: Unrecognized option \"$1\"" >&2
            ;;
        *)
            ARRAY[$count]=$1
            ((count++))
            ;;
    esac
    shift
  done

}

########################################################
# check arguments
########################################################

exit_if_empty ()
{
  local desc val

  desc="$1"
  shift
  val="$*"

  if [ -z "$val" ]
  then
    echo ERROR: "No argument given with \"$desc\" command line argument!" >&2
    exit 1
  fi
}

########################################################
# check files
########################################################

check_files ()
{
  if [ -z "$COMMAND" ];
  then
    echo "$FUNCNAME ERROR - no command defined."
      help
    exit 1
  fi
  
  SIZE_OF_ARRAY="${#ARRAY[@]}"
  if [ "$SIZE_OF_ARRAY" -eq 0 ]
  then
      echo 'ERROR: No files given!' >&2
      help
      exit 1
  fi

  i=0
  while [ "$i" -lt "$SIZE_OF_ARRAY" ]
  do
    if [ ! -f "${ARRAY[$i]}" ] && [ ! -d "${ARRAY[$i]}" ]; then
      echo ERROR: File or directory ${ARRAY[$i]} not found
      help
      exit 1
    fi
    ((i++))
  done

}

########################################################
# get # of cpus
########################################################
# modified code from
# PPSS, the Parallel Processing Shell Script
# 
# Copyright (c) 2009, Louwrentius
# All rights reserved.

get_no_of_cpus () {

  CPUINFO=/proc/cpuinfo
  ARCH=`uname`

  if [ -z "$NUMBER_OF_JOBS" ]; then
    if [ "$ARCH" == "Linux" ]
    then
      NUMBER_OF_JOBS=`grep ^processor $CPUINFO | wc -l`
  
    elif [ "$ARCH" == "Darwin" ]
    then
      NUMBER_OF_JOBS=`sysctl -a hw | grep -w logicalcpu | awk '{ print $2 }'`
  
    elif [ "$ARCH" == "CYGWIN_NT" ] || [ "$ARCH" == "MSYS_NT" ] || [ "$ARCH" == "MINGW32_NT" ] || [ "$ARCH" == "MINGW64_NT" ]
    then
      NUMBER_OF_JOBS=`wmic cpu get NumberOfLogicalProcessors | grep -v NumberOfLogicalProcessors`
  
    else
      NUMBER_OF_JOBS=`grep ^processor $CPUINFO | wc -l`
    fi
  
  fi
}

########################################################
# get # of processes w.r.t. available memory
########################################################

get_no_processes () {

  ARCH=`uname`

  if [ "$ARCH" == "Linux" ]
  then
    # Get total installed memory in MB
    mem_total=$(grep MemTotal /proc/meminfo | awk '{print $2}')

    # Convert KB to GB
    mem_gb=$(echo "$mem_total / 1024 / 1024" | bc)

  elif [ "$ARCH" == "Darwin" ]
  then
    # Get total installed memory in bytes
    mem_total=$(sysctl hw.memsize | awk '{print $2}')

    # Convert bytes to GB
    mem_gb=$(echo "$mem_total / 1024 / 1024 / 1024" | bc)

  elif [ "$ARCH" == "CYGWIN_NT" ] || [ "$ARCH" == "MSYS_NT" ] || [ "$ARCH" == "MINGW32_NT" ] || [ "$ARCH" == "MINGW64_NT" ]
  then
    # Get total installed memory in KB
    mem_total=$(wmic ComputerSystem get TotalPhysicalMemory | grep -Eo '[0-9]+')

    # Convert bytes to GB
    mem_gb=$(echo "$mem_total / 1024 / 1024 / 1024" | bc)
  else
    echo "System $ARCH not recognized"
    exit 1
  fi
    
  echo $mem_gb
  # Calculate number of processes (at least 1) and require 10GB memory for each process
  NUMBER_OF_JOBS=$(echo "if ($mem_gb < 10) 1 else $mem_gb / $MEM_LIMIT" | bc)
}

########################################################
# run parallelize
########################################################

parallelize ()
{
    
  SIZE_OF_ARRAY="${#ARRAY[@]}"

  # if number of processors is equal 0 call command serially
  if [ "$NUMBER_OF_JOBS" -eq "0" ]; then
    i=0
    while [ "$i" -lt "$SIZE_OF_ARRAY" ]
    do
      $COMMAND ${ARRAY[$i]}; 
      ((i++))
    done
    return
  fi

  BLOCK=$((10000* $SIZE_OF_ARRAY / $NUMBER_OF_JOBS ))

  i=0
  while [ "$i" -lt "$SIZE_OF_ARRAY" ]
  do
    count=$((10000* $i / $BLOCK ))
    if [ -z "${ARG_LIST[$count]}" ]; then
      ARG_LIST[$count]="${ARRAY[$i]}"
    else
      ARG_LIST[$count]="${ARG_LIST[$count]} ${ARRAY[$i]}"
    fi
    ((i++))
  done

  if [ -z "${LOGDIR}" ]; then
    LOGDIR=$PWD
  fi

  log=${LOGDIR}/parallelize_${HOSTNAME}_${time}.log
  if [ -z "${TEST}" ]; then
    echo Check $log for logging information
    echo > $log
    echo
  fi
  
  i=0
  
  while [ "$i" -lt "$NUMBER_OF_JOBS" ]
  do
    if [ ! "${ARG_LIST[$i]}" == "" ]; then
      j=$(($i+1))
      echo job ${j}/"$NUMBER_OF_JOBS":
      echo $COMMAND ${ARG_LIST[$i]}
      if [ -z "${TEST}" ]; then
        if [ -n "${LOGDIR}" ]; then
          echo job ${j}/"$NUMBER_OF_JOBS": $COMMAND ${ARG_LIST[$i]} >> $log
          nohup bash -c "for k in ${ARG_LIST[$i]}; do $COMMAND \$k; done" >> $log 2>&1 &
        else
          nohup bash -c "for k in ${ARG_LIST[$i]}; do $COMMAND \$k; done" >> /tmp/nohup.log 2>&1 &
        fi
      fi
    fi
    ((i++))
  done
}

########################################################
# help
########################################################

help ()
{
cat <<__EOM__

USAGE:
  parallelize [-p number_of_processes] [-l log_folder] [-t] -c command_to_parallelize filename|filepattern
  
  -p  <NUMBER>| --processes <NUMBER>  number of parallel jobs (=number of processors)
                                      (default $NUMBER_OF_JOBS)
  -c  <STRING>| --command <STRING>    command that should be parallelized
  -t          | --test                do not call command, but print files to be processed
  -l <Dir>    | --logdir <DIR>        directory where log-file will be saved
  -m <INT>    | --mem-limit <INT>     memory limit for each process (default $MEM_LIMIT)

   Only one filename or pattern is allowed. This can be either a single file or a pattern
   with wildcards to process multiple files. Optionally you can set number of processes,
   that are automatically set to the number of processors as default.

PURPOSE:
   Parallelize a job or command

OUTPUT:
   parallelize_${HOSTNAME}_${time}.log with current data and time in name as log-file if logdir is defined

EXAMPLE
   parallelize -c "niismooth -v -fwhm 8" sTRIO*.nii
     Parallelize smoothing with fwhm of 8mm for all files sTRIO*.nii. Use
     verbose mode to see diagnostic output.
   
   parallelize -c gunzip *.zip
     Parallelize unzipping of all zip-files in current folder. 

   parallelize -m 10 -c "T1prep.sh --no-surf" sTRIO*.nii
     Parallelize T1prep.sh without surface estimation and consider that each 
     process needs 10GB RAM. 

This script was written by Christian Gaser (christian.gaser@uni-jena.de).
This is ${version}.

__EOM__
}

########################################################
# call main program
########################################################

main ${1+"$@"}

