name: Update Dockerfile

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  bump-dockerfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update Dockerfile
        run: |
          tag=${{ github.event.release.tag_name }}
          sed -i -E "s/ARG T1PREP_VERSION=.*/ARG T1PREP_VERSION=${tag}/" Dockerfile
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git commit -am "chore: bump Dockerfile to ${tag}"
          git push
